from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class FrogBossAssets: 


	# Image Rule Assets
	# 左边竞猜 
	I_BET_LEFT = RuleImage(roi_front=(280,310,125,90), roi_back=(230,275,220,160), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_bet_left.png")
	I_BET_RIGHT = RuleImage(roi_front=(1095,310,125,90), roi_back=(1045,275,220,160), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_bet_right.png")
	# description 
	I_BET_SUCCESS_BOX = RuleImage(roi_front=(700,418,115,80), roi_back=(640,380,260,170), threshold=0.75, method="Template matching", file="./tasks/FrogBoss/fb/fb_bet_success_box.png")
	# 左边赢了 
	I_SUCCESS_LEFT = RuleImage(roi_front=(123,316,100,100), roi_back=(91,254,202,221), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_success_left.png")
	# 右边输了 
	I_FAILURE_RIGHT = RuleImage(roi_front=(1063,291,100,100), roi_back=(993,242,224,199), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_failure_right.png")
	# description 
	I_NEXT_COMPETITION = RuleImage(roi_front=(764,484,64,64), roi_back=(700,450,190,140), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_next_competition.png")
	# 30万金币 
	I_GOLD_30 = RuleImage(roi_front=(858,494,78,76), roi_back=(809,427,147,187), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_gold_30.png")
	# 确认竞猜 
	I_BET_SURE = RuleImage(roi_front=(1025,402,100,100), roi_back=(1000,297,200,226), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_bet_sure.png")
	# description 
	I_GOLD_30_CHECK = RuleImage(roi_front=(513,196,58,53), roi_back=(402,141,459,489), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_gold_30_check.png")
	# description 
	I_BETTED = RuleImage(roi_front=(1118,322,128,50), roi_back=(700,270,580,170), threshold=0.75, method="Template matching", file="./tasks/FrogBoss/fb/fb_betted.png")
	# 已竞猜鼓出现在押注的一侧(押左在左/押右在右), 左右各一张模板; 0.75容忍跨帧光照, 负向仅0.33
	I_BETTED_LEFT = RuleImage(roi_front=(262,307,150,52), roi_back=(150,270,580,170), threshold=0.75, method="Template matching", file="./tasks/FrogBoss/fb/fb_betted_left.png")
	# description 
	I_SUCCESS_RIGHT = RuleImage(roi_front=(1048,341,122,116), roi_back=(999,243,201,260), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_success_right.png")
	# description 
	I_FAILURE_LEFT = RuleImage(roi_front=(116,307,100,100), roi_back=(76,256,193,219), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_failure_left.png")
	# description 
	I_BET_FAILURE = RuleImage(roi_front=(612,258,270,68), roi_back=(540,220,400,160), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_bet_failure.png")
	# description 
	I_BET_SUCCESS = RuleImage(roi_front=(608,280,272,58), roi_back=(540,240,420,160), threshold=0.75, method="Template matching", file="./tasks/FrogBoss/fb/fb_bet_success.png")


	# Image Rule Assets
	# description 
	I_FROG_BOSS_ENTER = RuleImage(roi_front=(1191,391,36,38), roi_back=(1174,135,78,320), threshold=0.7, method="Template matching", file="./tasks/FrogBoss/fb/fb_frog_boss_enter.png")
	# 休息中 
	I_FROG_BOSS_REST = RuleImage(roi_front=(510,274,169,64), roi_back=(492,260,220,113), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_frog_boss_rest.png")


	# Ocr Rule Assets
	# Ocr-description 
	O_LEFT_COUNT = RuleOcr(roi=(308,470,90,48), area=(308,470,90,48), mode="Digit", method="Default", keyword="", name="left_count")
	O_RIGHT_COUNT = RuleOcr(roi=(1150,470,58,48), area=(1150,470,58,48), mode="Digit", method="Default", keyword="", name="right_count")
	# Ocr-description 
	O_TIME_REMAIN = RuleOcr(roi=(594,564,91,35), area=(594,564,91,35), mode="Duration", method="Default", keyword="", name="time_remain")


