from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class ActivityShikigamiAssets:


	# Click Rule Assets
	# description
	C_RANDOM_LEFT = RuleClick(roi_front=(17,84,104,356), roi_back=(17,81,106,365), name="random_left")
	# description
	C_RANDOM_RIGHT = RuleClick(roi_front=(1133,88,131,361), roi_back=(1131,84,133,363), name="random_right")
	# description
	C_RANDOM_TOP = RuleClick(roi_front=(126,66,989,58), roi_back=(123,65,991,58), name="random_top")
	# description
	C_RANDOM_BOTTOM = RuleClick(roi_front=(196,598,581,78), roi_back=(194,597,583,81), name="random_bottom")
	# description
	C_RANDOM_ALL = RuleClick(roi_front=(42,94,1207,543), roi_back=(42,94,1207,543), name="random_all")


	# Image Rule Assets
	# 庭院右栏活动入口icon
	I_SHI = RuleImage(roi_front=(1180,138,50,52), roi_back=(1150,105,125,120), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/as/as_shi.png")
	# 活动总览页标志
	I_CHECK_ACT_LIST = RuleImage(roi_front=(148,17,130,42), roi_back=(100,5,260,75), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_check_act_list.png")
	# 活动总览右下角前往活动按钮
	I_GOTO_ACT = RuleImage(roi_front=(1040,633,200,48), roi_back=(1000,610,280,95), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_goto_act.png")
	# 拾光永恒活动主界面标志
	I_CHECK_MAIN = RuleImage(roi_front=(148,12,155,44), roi_back=(100,5,310,75), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_check_main.png")
	# 回响之地入口
	I_GOTO_MAP = RuleImage(roi_front=(318,173,98,98), roi_back=(280,140,180,170), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/as/as_goto_map.png")
	# 亗地回响地图标志
	I_CHECK_MAP = RuleImage(roi_front=(155,12,140,46), roi_back=(100,5,310,75), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_check_map.png")
	# 地图上空余的上阵加号
	I_DEPLOY_PLUS = RuleImage(roi_front=(326,133,42,42), roi_back=(230,60,400,530), threshold=0.75, method="Template matching", file="./tasks/ActivityShikigami/as/as_deploy_plus.png")
	# 地图中央虚无精锐标签
	I_BOSS_LABEL = RuleImage(roi_front=(565,385,175,42), roi_back=(450,350,400,150), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_boss_label.png")
	# 派遣面板上阵按钮(金灰同结构,金色判定用match_brightness)
	I_DEPLOY = RuleImage(roi_front=(1000,466,108,39), roi_back=(950,440,220,95), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_deploy.png")
	# 白石晶宝箱弹窗关闭按钮(合战派遣奖励弹出)
	I_CHEST_CLOSE = RuleImage(roi_front=(1017,97,44,46), roi_back=(990,80,100,80), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_chest_close.png")
	# 神木补给界面关闭按钮(每日首次进活动弹出,发当日门票)
	I_SUPPLY_CLOSE = RuleImage(roi_front=(1135,172,43,46), roi_back=(1100,150,110,90), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_supply_close.png")
	# 合战派遣底部选择栏第一个阴阳师卡位
	C_HEZHAN_FIRST = RuleClick(roi_front=(80,560,110,120), roi_back=(80,560,110,120), name="hezhan_first")
	# 派遣面板放置时间加号(灰色上阵时提档)
	C_HEZHAN_PLUS = RuleClick(roi_front=(1145,348,44,44), roi_back=(1145,348,44,44), name="hezhan_plus")
	# 亗地回响地图右侧空白安全点击区(清结算提示)
	C_MAP_BLANK = RuleClick(roi_front=(860,200,200,120), roi_back=(860,200,200,120), name="map_blank")
	# 地图左上空白区(放弃派遣时点击关闭面板)
	C_MAP_CLOSE = RuleClick(roi_front=(60,40,100,70), roi_back=(60,40,100,70), name="map_close")
	# 虚无精锐boss准备页标志
	I_CHECK_BATTLE_MAIN = RuleImage(roi_front=(158,14,165,42), roi_back=(100,5,360,75), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_check_battle_main.png")
	# boss准备页式神录按钮
	I_BATTLE_MAIN_TO_RECORDS = RuleImage(roi_front=(1006,556,52,52), roi_back=(965,530,140,105), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/as/as_battle_main_to_records.png")
	# AP模式标志(x6票)
	I_CLIMB_MODE_AP = RuleImage(roi_front=(1116,554,36,20), roi_back=(1100,545,130,40), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_climb_mode_ap.png")
	# PASS模式标志(灵符x1), 判断模式时须先测AP再测PASS
	I_CLIMB_MODE_PASS = RuleImage(roi_front=(1133,530,64,26), roi_back=(1105,518,140,50), threshold=0.85, method="Template matching", file="./tasks/ActivityShikigami/as/as_climb_mode_pass.png")
	# AP/PASS切换按键
	I_CLIMB_MODE_SWITCH = RuleImage(roi_front=(1236,543,22,30), roi_back=(1215,533,65,50), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_climb_mode_switch.png")
	# 阵容已锁定图标
	I_LOCK = RuleImage(roi_front=(790,647,40,40), roi_back=(740,615,120,85), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_lock.png")
	# 阵容未锁定图标
	I_UNLOCK = RuleImage(roi_front=(790,647,40,40), roi_back=(740,615,120,85), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_unlock.png")
	# 左上角返回
	I_BACK_GREEN = RuleImage(roi_front=(27,19,34,38), roi_back=(2,1,170,75), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_back_green.png")
	# 右上跳过按钮
	I_SKIP_BUTTON = RuleImage(roi_front=(1159,37,51,22), roi_back=(1141,27,86,43), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_skip_button.png")
	# 红色退出
	I_RED_EXIT = RuleImage(roi_front=(1162,96,39,38), roi_back=(1120,49,110,135), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_red_exit.png")
	# 确认跳过
	I_CONFIRM_SKIP = RuleImage(roi_front=(707,442,137,38), roi_back=(656,397,231,124), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_confirm_skip.png")
	# 战斗补给推荐礼包弹窗关闭按钮(爬塔过程弹出)
	I_GIFT_CLOSE = RuleImage(roi_front=(1167,88,34,36), roi_back=(1140,60,100,90), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_gift_close.png")
	# 活动主界面左下炼石成金首领入口
	I_GOTO_GOLD_BOSS = RuleImage(roi_front=(154,418,50,74), roi_back=(110,380,140,150), threshold=0.75, method="Template matching", file="./tasks/ActivityShikigami/as/as_goto_gold_boss.png")
	# 炼石成金boss页标题标志
	I_CHECK_GOLD_BOSS = RuleImage(roi_front=(152,14,133,45), roi_back=(100,5,310,75), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_check_gold_boss.png")


	# Ocr Rule Assets
	# 挑战按钮
	O_FIRE = RuleOcr(roi=(1120,605,80,70), area=(1105,590,110,100), mode="Single", method="Default", keyword="挑战", name="fire")
	# AP门票剩余数量
	O_REMAIN_AP = RuleOcr(roi=(800,18,44,34), area=(790,14,64,44), mode="Digit", method="Default", keyword="", name="remain_ap")
	# PASS门票剩余数量
	O_REMAIN_PASS = RuleOcr(roi=(1005,18,32,36), area=(998,14,45,44), mode="Digit", method="Default", keyword="", name="remain_pass")
	# 炼石成金挑战按钮
	O_BOSS_FIRE = RuleOcr(roi=(1110,575,120,75), area=(1095,560,150,105), mode="Single", method="Default", keyword="挑战", name="boss_fire")
	# 炼石成金挑战票数(x12)
	O_BOSS_REMAIN = RuleOcr(roi=(1167,638,52,26), area=(1155,630,75,42), mode="Digit", method="Default", keyword="", name="boss_remain")
